#!/usr/bin/env node
/**
 * Generate SKILLS.md — the catalog of skills, commands, and agents.
 *
 * Skills are grouped by the `category` field in each SKILL.md frontmatter.
 * Commands and agents are listed flat. Data comes entirely from frontmatter,
 * so the catalog stays honest as long as this runs.
 *
 * Usage:
 *   node scripts/ci/skills-catalog.js            # write SKILLS.md
 *   node scripts/ci/skills-catalog.js --stdout   # print, don't write
 *   node scripts/ci/skills-catalog.js --check    # exit 1 if SKILLS.md is stale
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '../..');
const OUTPUT_PATH = path.join(ROOT, 'SKILLS.md');

// Fixed display order; any unknown category is appended alphabetically.
const CATEGORY_ORDER = [
  'Code Review & Quality',
  'Testing & TDD',
  'Build, Debug & Merge',
  'Language & Framework Patterns',
  'Databases & Data',
  'DevOps & Deployment',
  'AI, Agents & LLM',
  'Second Brain & Vault',
  'Writing & Content',
  'Business & Research',
  'Docs & Lookup',
  'Workflow & Meta',
];

function parseFrontmatter(file) {
  const raw = fs.readFileSync(file, 'utf8');
  const m = raw.match(/^---\n([\s\S]*?)\n---/);
  if (!m) return null;
  const fm = {};
  for (const line of m[1].split('\n')) {
    const kv = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!kv) continue;
    let v = kv[2].trim();
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
      v = v.slice(1, -1);
    }
    fm[kv[1]] = v;
  }
  return fm;
}

// Collapse a description to its first sentence and make it table-safe.
function summarize(desc) {
  if (!desc) return '';
  const sentence = desc.split(/(?<=[.!?])\s/)[0].trim();
  return sentence.replace(/\|/g, '\\|');
}

function readSkills() {
  const dir = path.join(ROOT, 'skills');
  return fs.readdirSync(dir, { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => {
      const file = path.join(dir, entry.name, 'SKILL.md');
      if (!fs.existsSync(file)) return null;
      const fm = parseFrontmatter(file);
      if (!fm) return null;
      return {
        name: fm.name || entry.name,
        desc: summarize(fm.description),
        category: fm.category || '',
        custom: /hackastak|staksmith/i.test(fm.origin || ''),
        loc: `skills/${entry.name}/SKILL.md`,
      };
    })
    .filter(Boolean)
    .sort((a, b) => a.name.localeCompare(b.name));
}

function readFlat(subdir, prefix) {
  const dir = path.join(ROOT, subdir);
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.md') && f !== 'README.md')
    .map(f => {
      const fm = parseFrontmatter(path.join(dir, f)) || {};
      return {
        name: (fm.name || f.replace(/\.md$/, '')),
        desc: summarize(fm.description),
        loc: `${subdir}/${f}`,
        prefix,
      };
    })
    .sort((a, b) => a.name.localeCompare(b.name));
}

function orderedCategories(present) {
  const known = CATEGORY_ORDER.filter(c => present.has(c));
  const extra = [...present].filter(c => !CATEGORY_ORDER.includes(c)).sort();
  return [...known, ...extra];
}

function render() {
  const skills = readSkills();
  const commands = readFlat('commands', '/');
  const agents = readFlat('agents', '');

  const uncategorized = skills.filter(s => !s.category).map(s => s.name);
  if (uncategorized.length) {
    throw new Error(`Skills missing a category field: ${uncategorized.join(', ')}`);
  }

  const groups = {};
  for (const s of skills) (groups[s.category] ||= []).push(s);

  const out = [];
  out.push('# Staksmith Skill Catalog');
  out.push('');
  out.push('> Auto-generated by `node scripts/ci/skills-catalog.js`. Do not edit by hand — update the source frontmatter and regenerate.');
  out.push('');
  out.push(`**${skills.length} skills · ${commands.length} commands · ${agents.length} agents**`);
  out.push('');
  out.push('Everything below is **plugin-distributed**: it installs with the plugin (`/plugin install staksmith@staksmith`). **Rules** are the exception — they are a separate manual install step (see the README, "Install rules"). Skills built for Staksmith are marked ⭐; the rest are inherited from the upstream ECC lineage.');
  out.push('');
  out.push('## Skills');
  out.push('');
  for (const cat of orderedCategories(new Set(Object.keys(groups)))) {
    const items = groups[cat];
    out.push(`### ${cat} (${items.length})`);
    out.push('');
    out.push('| Skill | What it does | Location |');
    out.push('| --- | --- | --- |');
    for (const s of items) {
      out.push(`| ${s.custom ? '⭐ ' : ''}\`${s.name}\` | ${s.desc} | \`${s.loc}\` |`);
    }
    out.push('');
  }

  out.push('## Commands');
  out.push('');
  out.push('| Command | What it does | Location |');
  out.push('| --- | --- | --- |');
  for (const c of commands) out.push(`| \`/${c.name}\` | ${c.desc} | \`${c.loc}\` |`);
  out.push('');

  out.push('## Agents');
  out.push('');
  out.push('| Agent | What it does | Location |');
  out.push('| --- | --- | --- |');
  for (const a of agents) out.push(`| \`${a.name}\` | ${a.desc} | \`${a.loc}\` |`);
  out.push('');

  return out.join('\n');
}

function main() {
  const content = render();
  if (process.argv.includes('--stdout')) {
    process.stdout.write(content);
    return;
  }
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(OUTPUT_PATH) ? fs.readFileSync(OUTPUT_PATH, 'utf8') : '';
    if (current !== content) {
      console.error('SKILLS.md is out of date. Run: node scripts/ci/skills-catalog.js');
      process.exit(1);
    }
    console.log('SKILLS.md is up to date.');
    return;
  }
  fs.writeFileSync(OUTPUT_PATH, content);
  console.log(`Wrote ${path.relative(ROOT, OUTPUT_PATH)} (${content.split('\n').length} lines).`);
}

if (require.main === module) main();

module.exports = { render, readSkills, CATEGORY_ORDER };
